tasks:
  - init: |
      curl -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
      unzip -q cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
      mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
      export ANDROID_HOME=$HOME/android-sdk
      export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
      yes | sdkmanager --licenses
      sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
      echo "sdk.dir=$ANDROID_HOME" > local.properties
      gradle wrapper --gradle-version 8.6
